### ISSUE TITLE
Can't change language from OSK

### ISSUE THREAD

**Issue by astro-ray** [hallelujahdrive/impanel-with-osk#3]
One can change language from gnome OSK but, after imstalling the extension, this feature isn't working.

![image](https://github.com/user-attachments/assets/820ffffb-5d53-443c-9a48-d9b10f69e047)

**Comment by astro-ray** [comment]
Ok, something to add to this, single cliks doesn't bring up the keyboard settings, but long press does, but the menu disappears as soon as I lift the finger.

[Screencast from 2024-08-24 18-04-18.webm](https://github.com/user-attachments/assets/0730ad10-a9a8-414c-89c2-398f681956ca)

I am on Fedora 40, Gnome 46

**Comment by hallelujahdrive** [comment]
@astro-ray 

Thanks for reporting the issue.
Access to keyboard settings was not really necessary for me, so I assigned it to a long press on the language key for now, but it does not seem to be working properly.
I will attempt to resolve this issue.
